# Generated by Django 5.0.7 on 2024-07-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaOrNoodles', '0003_counter_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoodleCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noodleCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
